// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Usql client for Direktiv",
    "title": "usql",
    "version": "1.0.0",
    "x-direktiv-meta": {
      "category": "Database",
      "container": "direktiv/usql",
      "issues": "https://github.com/direktiv-apps/usql/issues",
      "license": "[Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0)",
      "long-description": "[Usql](https://github.com/xo/usql) is a universal command-line interface for PostgreSQL, MySQL, Oracle Database, SQLite3, Microsoft SQL Server, and many other databases including NoSQL and non-relational databases. \nThis service provides easy access to database from Direktiv and supports variables and interpolation as well. ",
      "maintainer": "[direktiv.io](https://www.direktiv.io)",
      "url": "https://github.com/direktiv-apps/usql"
    }
  },
  "paths": {
    "/": {
      "post": {
        "parameters": [
          {
            "type": "string",
            "description": "direktiv action id is an UUID. \nFor development it can be set to 'development'\n",
            "name": "Direktiv-ActionID",
            "in": "header"
          },
          {
            "type": "string",
            "description": "direktiv temp dir is the working directory for that request\nFor development it can be set to e.g. '/tmp'\n",
            "name": "Direktiv-TempDir",
            "in": "header"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "connection"
              ],
              "properties": {
                "connection": {
                  "description": "Connection string for sql commands. This will be used for all commands and has to be URL-encoded.",
                  "type": "string",
                  "example": "pg://myuser:mypwd@MYDATABAESERVER:5432"
                },
                "queries": {
                  "description": "List of sql commands. Commands can use interpolation:\u003cbr/\u003e query: select * from table where id = :'ID'\u003cbr/\u003e args: ID=123\n",
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "args": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        },
                        "example": "ARG=myarg"
                      },
                      "query": {
                        "type": "string",
                        "example": "select * from table where value = :'ARG'"
                      }
                    }
                  },
                  "example": {
                    "args": [
                      "KEY=1"
                    ],
                    "query": "select * from mytable where key = :'KEY'"
                  }
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "nice greeting",
            "schema": {
              "type": "object",
              "properties": {
                "queries": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "result": {
                        "type": "object",
                        "additionalProperties": false
                      },
                      "success": {
                        "type": "boolean"
                      }
                    }
                  }
                }
              },
              "example": {
                "queries": [
                  {
                    "result": [
                      {
                        "id": 123,
                        "name": "John"
                      }
                    ],
                    "success": true
                  },
                  {
                    "result": "INSERT 1",
                    "success": true
                  }
                ]
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            },
            "headers": {
              "Direktiv-ErrorCode": {
                "type": "string"
              },
              "Direktiv-ErrorMessage": {
                "type": "string"
              }
            }
          }
        },
        "x-direktiv": {
          "cmds": [
            {
              "action": "foreach",
              "exec": "usql {{ .Body.Connection }} -c \"{{ .Item.Query }}\" -J --set SHOW_HOST_INFORMATION=false \n{{- range .Item.Args }} --set={{.}} {{- end}}",
              "loop": ".Queries"
            }
          ],
          "output": "{\n  \"queries\": {{  index . 0 | toJson }}\n}\n"
        },
        "x-direktiv-errors": {
          "io.direktiv.command.error": "Command execution failed",
          "io.direktiv.output.error": "Template error for output generation of the service",
          "io.direktiv.ri.error": "Can not create information object from request"
        },
        "x-direktiv-examples": [
          {
            "content": "- id: query\n     type: action\n     action:\n       function: usql",
            "title": "Basic"
          }
        ],
        "x-direktiv-function": "functions:\n  - id: usql\n    image: direktiv/usql\n    type: knative-workflow"
      },
      "delete": {
        "parameters": [
          {
            "type": "string",
            "description": "On cancel Direktiv sends a DELETE request to\nthe action with id in the header\n",
            "name": "Direktiv-ActionID",
            "in": "header"
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "x-direktiv": {
          "cancel": "echo 'cancel {{ .DirektivActionID }}'"
        }
      }
    }
  },
  "definitions": {
    "direktivFile": {
      "type": "object",
      "x-go-type": {
        "import": {
          "package": "github.com/direktiv/apps/go/pkg/apps"
        },
        "type": "DirektivFile"
      }
    },
    "error": {
      "type": "object",
      "required": [
        "errorCode",
        "errorMessage"
      ],
      "properties": {
        "errorCode": {
          "type": "string"
        },
        "errorMessage": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Usql client for Direktiv",
    "title": "usql",
    "version": "1.0.0",
    "x-direktiv-meta": {
      "category": "Database",
      "container": "direktiv/usql",
      "issues": "https://github.com/direktiv-apps/usql/issues",
      "license": "[Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0)",
      "long-description": "[Usql](https://github.com/xo/usql) is a universal command-line interface for PostgreSQL, MySQL, Oracle Database, SQLite3, Microsoft SQL Server, and many other databases including NoSQL and non-relational databases. \nThis service provides easy access to database from Direktiv and supports variables and interpolation as well. ",
      "maintainer": "[direktiv.io](https://www.direktiv.io)",
      "url": "https://github.com/direktiv-apps/usql"
    }
  },
  "paths": {
    "/": {
      "post": {
        "parameters": [
          {
            "type": "string",
            "description": "direktiv action id is an UUID. \nFor development it can be set to 'development'\n",
            "name": "Direktiv-ActionID",
            "in": "header"
          },
          {
            "type": "string",
            "description": "direktiv temp dir is the working directory for that request\nFor development it can be set to e.g. '/tmp'\n",
            "name": "Direktiv-TempDir",
            "in": "header"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "connection"
              ],
              "properties": {
                "connection": {
                  "description": "Connection string for sql commands. This will be used for all commands and has to be URL-encoded.",
                  "type": "string",
                  "example": "pg://myuser:mypwd@MYDATABAESERVER:5432"
                },
                "queries": {
                  "description": "List of sql commands. Commands can use interpolation:\u003cbr/\u003e query: select * from table where id = :'ID'\u003cbr/\u003e args: ID=123\n",
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/QueriesItems0"
                  },
                  "example": {
                    "args": [
                      "KEY=1"
                    ],
                    "query": "select * from mytable where key = :'KEY'"
                  }
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "nice greeting",
            "schema": {
              "type": "object",
              "properties": {
                "queries": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/QueriesItems0"
                  }
                }
              },
              "example": {
                "queries": [
                  {
                    "result": [
                      {
                        "id": 123,
                        "name": "John"
                      }
                    ],
                    "success": true
                  },
                  {
                    "result": "INSERT 1",
                    "success": true
                  }
                ]
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            },
            "headers": {
              "Direktiv-ErrorCode": {
                "type": "string"
              },
              "Direktiv-ErrorMessage": {
                "type": "string"
              }
            }
          }
        },
        "x-direktiv": {
          "cmds": [
            {
              "action": "foreach",
              "exec": "usql {{ .Body.Connection }} -c \"{{ .Item.Query }}\" -J --set SHOW_HOST_INFORMATION=false \n{{- range .Item.Args }} --set={{.}} {{- end}}",
              "loop": ".Queries"
            }
          ],
          "output": "{\n  \"queries\": {{  index . 0 | toJson }}\n}\n"
        },
        "x-direktiv-errors": {
          "io.direktiv.command.error": "Command execution failed",
          "io.direktiv.output.error": "Template error for output generation of the service",
          "io.direktiv.ri.error": "Can not create information object from request"
        },
        "x-direktiv-examples": [
          {
            "content": "- id: query\n     type: action\n     action:\n       function: usql",
            "title": "Basic"
          }
        ],
        "x-direktiv-function": "functions:\n  - id: usql\n    image: direktiv/usql\n    type: knative-workflow"
      },
      "delete": {
        "parameters": [
          {
            "type": "string",
            "description": "On cancel Direktiv sends a DELETE request to\nthe action with id in the header\n",
            "name": "Direktiv-ActionID",
            "in": "header"
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "x-direktiv": {
          "cancel": "echo 'cancel {{ .DirektivActionID }}'"
        }
      }
    }
  },
  "definitions": {
    "QueriesItems0": {
      "type": "object",
      "properties": {
        "result": {
          "type": "object",
          "additionalProperties": false
        },
        "success": {
          "type": "boolean"
        }
      }
    },
    "direktivFile": {
      "type": "object",
      "x-go-type": {
        "import": {
          "package": "github.com/direktiv/apps/go/pkg/apps"
        },
        "type": "DirektivFile"
      }
    },
    "error": {
      "type": "object",
      "required": [
        "errorCode",
        "errorMessage"
      ],
      "properties": {
        "errorCode": {
          "type": "string"
        },
        "errorMessage": {
          "type": "string"
        }
      }
    }
  }
}`))
}
